"""Add OBE models

Revision ID: 78b3f2bec705
Revises: 6630d9e09bfe
Create Date: 2026-05-31 18:19:19.499014
"""

from alembic import op
import sqlalchemy as sa



revision = '78b3f2bec705'
down_revision = '6630d9e09bfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('alignment_matrix', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('module_number', sa.Integer(), nullable=False),
    sa.Column('lecture_no', sa.Integer(), nullable=False),
    sa.Column('session_topic', sa.String(length=500), nullable=False),
    sa.Column('rbt_levels', sa.JSON(), nullable=False),
    sa.Column('course_outcomes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_plans')
    op.drop_table('assessment_plans')
    # ### end Alembic commands ###
